server:
  port: 9908

spring:
  application:
    name: miracle-gateway

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
          - id: common
          uri: 127.0.0.1:9018
          predicates:
          - Path=/**


    sentinel:
      transport:
        dashboard: 127.0.0.1:9670
        # 客户端监控API的端口
        port: 8877
      # 使用nacos持久化sentinel限流规则
#      datasource:
#        ds1:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            dataId: miracle-gateway
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow



  #redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
        shutdown-timeout: 400ms



management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false