server:
  port: 9488


spring:
  application:
    name: miracle-sentinel

  cloud:
    nacos:
      discovery:
            server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        dashboard: 127.0.0.1:9670
        # 客户端监控API的端口
        port: 8877
      # 使用nacos持久化sentinel限流规则
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8466
            dataId: miracle-sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

#       [
#          {
#              "resource": "/system/user/login",
#              "limitApp": "default",
#              "grade": 1,
#              "count": 2,
#              "strategy": 0,
#              "controlBehavior": 0,
#              "clusterMode": false
#          }
#       ]